CREATE ROWSTORE TABLE `activation_data` (
  `data_id` bigint(20) NOT NULL AUTO_INCREMENT,
  `user_id` int(5) unsigned NOT NULL,
  `ems_id` int(5) unsigned NOT NULL,
  `activation_id` bigint(20) unsigned DEFAULT NULL,
  `user_activation_rule_entity_id` bigint(20) unsigned DEFAULT NULL,
  `created_date` date DEFAULT NULL,
  `user_name` varchar(45) CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL DEFAULT '',
  `status` varchar(50) CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL,
  `user_result_id` bigint(20) DEFAULT NULL,
  `created_ts` datetime NOT NULL,
  `name` varchar(100) CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL,
  `activation_data_na_id` bigint(20) DEFAULT NULL,
  `user_condition_id` bigint(10) DEFAULT NULL,
  `pending_action_taken` bit(1) NOT NULL DEFAULT '\0',
  `work_item_id` varchar(100) CHARACTER SET utf8 COLLATE utf8_general_ci DEFAULT NULL,
  `scheduled_ts` datetime DEFAULT NULL,
  `location_id` bigint(20) DEFAULT NULL,
  `modified_ts` datetime DEFAULT NULL,
  PRIMARY KEY (`data_id`),
  KEY `idx_4` (`name`,`status`),
  KEY `idx_12` (`activation_id`),
  KEY `idx_3` (`created_date`,`user_id`,`status`),
  KEY `idx_7` (`data_id`,`user_id`,`ems_id`,`created_date`),
  KEY `idx_10` (`created_date`,`user_name`,`user_id`,`parameter_full_name`),
  KEY `idx_2` (`user_id`,`user_name`,`cell_id`,`created_date`,`parameter_full_name`,`mo_name`),
  KEY `idx_5` (`data_id`,`ems_id`,`user_name`),
  KEY `idx_9` (`created_date`,`user_id`,`ems_id`,`user_activation_rule_entity_id`,`user_name`),
  KEY `idx_13` (`status`,`schedule_type`,`ems_id`),
  KEY `idx_15` (`parameter_full_name`,`status`)
) AUTO_INCREMENT=350051483 AUTOSTATS_CARDINALITY_MODE=PERIODIC AUTOSTATS_HISTOGRAM_MODE=CREATE SQL_MODE='STRICT_ALL_TABLES'