CREATE ROWSTORE TABLE `activation_data` (
  `data_id` bigint(20) NOT NULL AUTO_INCREMENT,
  `algorithm_id` int(5) unsigned NOT NULL,
  `ems_id` int(5) unsigned NOT NULL,
  `owner_id` varchar(15) CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL,
  `activation_id` bigint(20) unsigned DEFAULT NULL,
  `algorithm_activation_rule_entity_id` bigint(20) unsigned DEFAULT NULL,
  `created_date` date DEFAULT NULL,
  `enodeb_name` varchar(45) CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL DEFAULT '',
  `status` varchar(50) CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL,
  `cell_id` varchar(20) CHARACTER SET utf8 COLLATE utf8_general_ci DEFAULT NULL,
  `details` varchar(2000) CHARACTER SET utf8 COLLATE utf8_general_ci DEFAULT NULL,
  `parameter_full_name` varchar(300) CHARACTER SET utf8 COLLATE utf8_general_ci DEFAULT NULL,
  `new_value` varchar(2000) CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL,
  `old_value` varchar(2000) CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL,
  `algorithm_result_id` bigint(20) DEFAULT NULL,
  `created_ts` datetime NOT NULL,
  `name` varchar(100) CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL,
  `enodeb_full_name` varchar(100) CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL,
  `mo_name` varchar(500) CHARACTER SET utf8 COLLATE utf8_general_ci DEFAULT NULL,
  `parameter_name` varchar(300) CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL,
  `parameter_operation` varchar(50) CHARACTER SET utf8 COLLATE utf8_general_ci DEFAULT NULL,
  `software_ver` varchar(100) CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL,
  `execution_type` varchar(50) CHARACTER SET utf8 COLLATE utf8_general_ci DEFAULT NULL,
  `schedule_type` varchar(50) CHARACTER SET utf8 COLLATE utf8_general_ci DEFAULT NULL,
  `activation_data_na_id` bigint(20) DEFAULT NULL,
  `algorithm_condition_id` bigint(10) DEFAULT NULL,
  `pending_action_taken` bit(1) NOT NULL DEFAULT '\0',
  `work_item_id` varchar(100) CHARACTER SET utf8 COLLATE utf8_general_ci DEFAULT NULL,
  `scheduled_ts` datetime DEFAULT NULL,
  `safety_check` bit(1) DEFAULT '\0',
  `status_reason` varchar(53) CHARACTER SET utf8 COLLATE utf8_general_ci DEFAULT NULL,
  `cl_eligibility` varchar(4) CHARACTER SET utf8 COLLATE utf8_general_ci DEFAULT NULL,
  `engagable_start_time` varchar(19) CHARACTER SET utf8 COLLATE utf8_general_ci DEFAULT NULL,
  `engagable_end_time` varchar(19) CHARACTER SET utf8 COLLATE utf8_general_ci DEFAULT NULL,
  `vas_eligible` varchar(4) CHARACTER SET utf8 COLLATE utf8_general_ci DEFAULT NULL,
  `dml_eligible` varchar(4) CHARACTER SET utf8 COLLATE utf8_general_ci DEFAULT NULL,
  `southbound_id` varchar(4) CHARACTER SET utf8 COLLATE utf8_general_ci DEFAULT NULL,
  `engagable_timezone` varchar(4) CHARACTER SET utf8 COLLATE utf8_general_ci DEFAULT NULL,
  `mkt_id` varchar(3) CHARACTER SET utf8 COLLATE utf8_general_ci DEFAULT NULL,
  `gnb_du_id` varchar(20) CHARACTER SET utf8 COLLATE utf8_general_ci DEFAULT NULL,
  `kirke_id` bigint(20) DEFAULT NULL,
  `kirke_status` varchar(45) CHARACTER SET utf8 COLLATE utf8_general_ci DEFAULT NULL,
  `location_id` bigint(20) DEFAULT NULL,
  `modified_ts` datetime DEFAULT NULL,
  PRIMARY KEY (`data_id`),
  KEY `idx_4` (`name`,`status`),
  KEY `idx_12` (`activation_id`),
  KEY `idx_3` (`created_date`,`algorithm_id`,`status`),
  KEY `idx_7` (`data_id`,`algorithm_id`,`ems_id`,`created_date`),
  KEY `idx_10` (`created_date`,`enodeb_name`,`algorithm_id`,`parameter_full_name`),
  KEY `idx_2` (`algorithm_id`,`enodeb_name`,`cell_id`,`created_date`,`parameter_full_name`,`mo_name`),
  KEY `idx_5` (`data_id`,`ems_id`,`enodeb_name`),
  KEY `idx_9` (`created_date`,`algorithm_id`,`ems_id`,`algorithm_activation_rule_entity_id`,`enodeb_name`),
  KEY `idx_13` (`status`,`schedule_type`,`ems_id`),
  KEY `idx_15` (`parameter_full_name`,`status`)
) AUTO_INCREMENT=350051483 AUTOSTATS_CARDINALITY_MODE=PERIODIC AUTOSTATS_HISTOGRAM_MODE=CREATE SQL_MODE='STRICT_ALL_TABLES'